### ISSUE TITLE
Alpharetta GA Tech Companies

### ISSUE THREAD

**Issue by beardofedu** [github-scholars/atlanta-june#4]
ATC Companies
Advanced Technology Development Center (ATDC)
Edge Solutions
Georgia Power
Greater North Fulton Chamber of Commerce
Greater Alpharetta Tech Network
Lexis Nexis
McKesson
Gwinnett Technical College
Hewlett-Packard
Infor
Jackson Healthcare
Lancope
Microsoft
Priority Payment Systems
Pyramid Consulting, Inc.
Metro Atlanta Chamber of Commerce
Siemens Industry, Inc.
Technology Association of Georgia
ThyssenKrupp IT Services
Verint Systems
Verizon Wireless

**Comment by Taylor2002** [comment]
hello
